apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  sources:
    - chart: redis
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 17.10.2
    - chart: prometheus-redis-exporter
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 5.3.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

