apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: directory-app
  namespace: argocd
spec:
  project: default

  destination:
    namespace: directory-app
    server: "https://kubernetes.default.svc"

  source:
    path: guestbook-with-sub-directories
    repoURL: "https://github.com/shivasaicharanruthala/LearnArgoCD.git"
    targetRevision: main
    di

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
