apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  project: default

  destination:
    namespace: helm-app
    server: "https://kubernetes.default.svc"

  source:
    path: helm-guestbook
    repoURL: "https://github.com/shivasaicharanruthala/LearnArgoCD.git"
    targetRevision: main
    helm:
      releaseName: my-helm-guestbook-release

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
